// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/danmu.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DanmuIdRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DanmuIdRequest) Reset()         { *m = DanmuIdRequest{} }
func (m *DanmuIdRequest) String() string { return proto.CompactTextString(m) }
func (*DanmuIdRequest) ProtoMessage()    {}
func (*DanmuIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c26fdfc8ec018a8, []int{0}
}

func (m *DanmuIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmuIdRequest.Unmarshal(m, b)
}
func (m *DanmuIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmuIdRequest.Marshal(b, m, deterministic)
}
func (m *DanmuIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmuIdRequest.Merge(m, src)
}
func (m *DanmuIdRequest) XXX_Size() int {
	return xxx_messageInfo_DanmuIdRequest.Size(m)
}
func (m *DanmuIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmuIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DanmuIdRequest proto.InternalMessageInfo

func (m *DanmuIdRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DanmuUIdRequest struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DanmuUIdRequest) Reset()         { *m = DanmuUIdRequest{} }
func (m *DanmuUIdRequest) String() string { return proto.CompactTextString(m) }
func (*DanmuUIdRequest) ProtoMessage()    {}
func (*DanmuUIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c26fdfc8ec018a8, []int{1}
}

func (m *DanmuUIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmuUIdRequest.Unmarshal(m, b)
}
func (m *DanmuUIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmuUIdRequest.Marshal(b, m, deterministic)
}
func (m *DanmuUIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmuUIdRequest.Merge(m, src)
}
func (m *DanmuUIdRequest) XXX_Size() int {
	return xxx_messageInfo_DanmuUIdRequest.Size(m)
}
func (m *DanmuUIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmuUIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DanmuUIdRequest proto.InternalMessageInfo

func (m *DanmuUIdRequest) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type DanmuRoomIdRequest struct {
	RoomId               uint32   `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DanmuRoomIdRequest) Reset()         { *m = DanmuRoomIdRequest{} }
func (m *DanmuRoomIdRequest) String() string { return proto.CompactTextString(m) }
func (*DanmuRoomIdRequest) ProtoMessage()    {}
func (*DanmuRoomIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c26fdfc8ec018a8, []int{2}
}

func (m *DanmuRoomIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmuRoomIdRequest.Unmarshal(m, b)
}
func (m *DanmuRoomIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmuRoomIdRequest.Marshal(b, m, deterministic)
}
func (m *DanmuRoomIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmuRoomIdRequest.Merge(m, src)
}
func (m *DanmuRoomIdRequest) XXX_Size() int {
	return xxx_messageInfo_DanmuRoomIdRequest.Size(m)
}
func (m *DanmuRoomIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmuRoomIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DanmuRoomIdRequest proto.InternalMessageInfo

func (m *DanmuRoomIdRequest) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type DanmuUIdAndRoomIdRequest struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId               uint32   `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DanmuUIdAndRoomIdRequest) Reset()         { *m = DanmuUIdAndRoomIdRequest{} }
func (m *DanmuUIdAndRoomIdRequest) String() string { return proto.CompactTextString(m) }
func (*DanmuUIdAndRoomIdRequest) ProtoMessage()    {}
func (*DanmuUIdAndRoomIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c26fdfc8ec018a8, []int{3}
}

func (m *DanmuUIdAndRoomIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmuUIdAndRoomIdRequest.Unmarshal(m, b)
}
func (m *DanmuUIdAndRoomIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmuUIdAndRoomIdRequest.Marshal(b, m, deterministic)
}
func (m *DanmuUIdAndRoomIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmuUIdAndRoomIdRequest.Merge(m, src)
}
func (m *DanmuUIdAndRoomIdRequest) XXX_Size() int {
	return xxx_messageInfo_DanmuUIdAndRoomIdRequest.Size(m)
}
func (m *DanmuUIdAndRoomIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmuUIdAndRoomIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DanmuUIdAndRoomIdRequest proto.InternalMessageInfo

func (m *DanmuUIdAndRoomIdRequest) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DanmuUIdAndRoomIdRequest) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type DanmuRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  uint32   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId               uint32   `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Visible              bool     `protobuf:"varint,4,opt,name=visible,proto3" json:"visible,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DanmuRequest) Reset()         { *m = DanmuRequest{} }
func (m *DanmuRequest) String() string { return proto.CompactTextString(m) }
func (*DanmuRequest) ProtoMessage()    {}
func (*DanmuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c26fdfc8ec018a8, []int{4}
}

func (m *DanmuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmuRequest.Unmarshal(m, b)
}
func (m *DanmuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmuRequest.Marshal(b, m, deterministic)
}
func (m *DanmuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmuRequest.Merge(m, src)
}
func (m *DanmuRequest) XXX_Size() int {
	return xxx_messageInfo_DanmuRequest.Size(m)
}
func (m *DanmuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DanmuRequest proto.InternalMessageInfo

func (m *DanmuRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DanmuRequest) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DanmuRequest) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *DanmuRequest) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *DanmuRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type DanmuResponse struct {
	Status               bool                    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	DanmuList            []*DanmuResponse_Result `protobuf:"bytes,2,rep,name=danmu_list,json=danmuList,proto3" json:"danmu_list,omitempty"`
	TimeUsed             int64                   `protobuf:"varint,3,opt,name=time_used,json=timeUsed,proto3" json:"time_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DanmuResponse) Reset()         { *m = DanmuResponse{} }
func (m *DanmuResponse) String() string { return proto.CompactTextString(m) }
func (*DanmuResponse) ProtoMessage()    {}
func (*DanmuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c26fdfc8ec018a8, []int{5}
}

func (m *DanmuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmuResponse.Unmarshal(m, b)
}
func (m *DanmuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmuResponse.Marshal(b, m, deterministic)
}
func (m *DanmuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmuResponse.Merge(m, src)
}
func (m *DanmuResponse) XXX_Size() int {
	return xxx_messageInfo_DanmuResponse.Size(m)
}
func (m *DanmuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DanmuResponse proto.InternalMessageInfo

func (m *DanmuResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *DanmuResponse) GetDanmuList() []*DanmuResponse_Result {
	if m != nil {
		return m.DanmuList
	}
	return nil
}

func (m *DanmuResponse) GetTimeUsed() int64 {
	if m != nil {
		return m.TimeUsed
	}
	return 0
}

type DanmuResponse_Result struct {
	Visible              bool     `protobuf:"varint,1,opt,name=visible,proto3" json:"visible,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DanmuResponse_Result) Reset()         { *m = DanmuResponse_Result{} }
func (m *DanmuResponse_Result) String() string { return proto.CompactTextString(m) }
func (*DanmuResponse_Result) ProtoMessage()    {}
func (*DanmuResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c26fdfc8ec018a8, []int{5, 0}
}

func (m *DanmuResponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmuResponse_Result.Unmarshal(m, b)
}
func (m *DanmuResponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmuResponse_Result.Marshal(b, m, deterministic)
}
func (m *DanmuResponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmuResponse_Result.Merge(m, src)
}
func (m *DanmuResponse_Result) XXX_Size() int {
	return xxx_messageInfo_DanmuResponse_Result.Size(m)
}
func (m *DanmuResponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmuResponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_DanmuResponse_Result proto.InternalMessageInfo

func (m *DanmuResponse_Result) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *DanmuResponse_Result) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type DanmuChangeResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DanmuChangeResponse) Reset()         { *m = DanmuChangeResponse{} }
func (m *DanmuChangeResponse) String() string { return proto.CompactTextString(m) }
func (*DanmuChangeResponse) ProtoMessage()    {}
func (*DanmuChangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c26fdfc8ec018a8, []int{6}
}

func (m *DanmuChangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmuChangeResponse.Unmarshal(m, b)
}
func (m *DanmuChangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmuChangeResponse.Marshal(b, m, deterministic)
}
func (m *DanmuChangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmuChangeResponse.Merge(m, src)
}
func (m *DanmuChangeResponse) XXX_Size() int {
	return xxx_messageInfo_DanmuChangeResponse.Size(m)
}
func (m *DanmuChangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmuChangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DanmuChangeResponse proto.InternalMessageInfo

func (m *DanmuChangeResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*DanmuIdRequest)(nil), "protobuf.DanmuIdRequest")
	proto.RegisterType((*DanmuUIdRequest)(nil), "protobuf.DanmuUIdRequest")
	proto.RegisterType((*DanmuRoomIdRequest)(nil), "protobuf.DanmuRoomIdRequest")
	proto.RegisterType((*DanmuUIdAndRoomIdRequest)(nil), "protobuf.DanmuUIdAndRoomIdRequest")
	proto.RegisterType((*DanmuRequest)(nil), "protobuf.DanmuRequest")
	proto.RegisterType((*DanmuResponse)(nil), "protobuf.DanmuResponse")
	proto.RegisterType((*DanmuResponse_Result)(nil), "protobuf.DanmuResponse.Result")
	proto.RegisterType((*DanmuChangeResponse)(nil), "protobuf.DanmuChangeResponse")
}

func init() { proto.RegisterFile("protobuf/danmu.proto", fileDescriptor_5c26fdfc8ec018a8) }

var fileDescriptor_5c26fdfc8ec018a8 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x86, 0x95, 0xa4, 0x0d, 0x61, 0x0a, 0x14, 0xb9, 0x15, 0xa4, 0xf4, 0x43, 0x51, 0x7a, 0xc9,
	0x85, 0x54, 0xa2, 0xd7, 0xf6, 0x90, 0xd2, 0xaa, 0x42, 0xea, 0xc9, 0x55, 0xce, 0x08, 0xb0, 0x77,
	0xd7, 0x12, 0x89, 0xd9, 0xd8, 0x41, 0xda, 0xc3, 0xfe, 0xb8, 0xfd, 0x5d, 0x7b, 0x59, 0xc5, 0x21,
	0x9f, 0x10, 0xed, 0xde, 0x3c, 0x33, 0xef, 0x3c, 0x9e, 0xd7, 0x1e, 0x78, 0x7f, 0x48, 0xb8, 0xe4,
	0xdb, 0xf4, 0xea, 0x1b, 0xd9, 0xc4, 0x51, 0xea, 0xab, 0x10, 0x59, 0x45, 0xd6, 0x75, 0x60, 0xf4,
	0x3b, 0x2b, 0xac, 0x08, 0xa6, 0xb7, 0x29, 0x15, 0x12, 0x8d, 0x40, 0x67, 0xc4, 0xd6, 0x1c, 0xcd,
	0x1b, 0x62, 0x9d, 0x11, 0xf7, 0x2b, 0xbc, 0x55, 0x8a, 0xb0, 0x92, 0x8c, 0xc1, 0x48, 0x4b, 0x4d,
	0x76, 0x74, 0xe7, 0x80, 0x94, 0x08, 0x73, 0x1e, 0x55, 0xba, 0x29, 0xf4, 0x12, 0xce, 0xa3, 0x75,
	0xa9, 0x35, 0x13, 0x55, 0x77, 0xff, 0x80, 0x5d, 0x30, 0x83, 0x98, 0x34, 0x9b, 0xce, 0xe0, 0x75,
	0x8c, 0xde, 0xc0, 0xdc, 0xc3, 0x20, 0xbf, 0xf5, 0xf2, 0xe8, 0x05, 0x4a, 0xbf, 0x88, 0x32, 0xea,
	0x28, 0x64, 0x43, 0xef, 0xc8, 0x04, 0xdb, 0xee, 0xa9, 0xfd, 0xca, 0xd1, 0x3c, 0x0b, 0x17, 0x61,
	0x56, 0xd9, 0xf1, 0x58, 0xd2, 0x58, 0xda, 0xaf, 0x1d, 0xcd, 0xeb, 0xe3, 0x22, 0x74, 0x1f, 0x34,
	0x18, 0x9e, 0xee, 0x17, 0x07, 0x1e, 0x0b, 0x8a, 0x26, 0x60, 0x0a, 0xb9, 0x91, 0xa9, 0x50, 0x43,
	0x58, 0xf8, 0x14, 0xa1, 0x9f, 0x00, 0xea, 0xf9, 0xd7, 0x7b, 0x26, 0xa4, 0xad, 0x3b, 0x86, 0xf7,
	0x66, 0xf1, 0xc5, 0x2f, 0x3e, 0xc1, 0x6f, 0x40, 0x7c, 0x4c, 0x45, 0xba, 0x97, 0xb8, 0xaf, 0x3a,
	0xfe, 0x31, 0x21, 0xd1, 0x47, 0xe8, 0x4b, 0x16, 0xd1, 0x75, 0x2a, 0x68, 0x3e, 0xb7, 0x81, 0xad,
	0x2c, 0x11, 0x0a, 0x4a, 0x66, 0x3f, 0xc0, 0xcc, 0x3b, 0xea, 0x1e, 0xb4, 0x4e, 0x0f, 0x7a, 0xd3,
	0xc3, 0x1c, 0xde, 0xa9, 0xdb, 0x97, 0x37, 0x9b, 0xf8, 0x9a, 0x3e, 0x67, 0x64, 0xf1, 0xa8, 0x9f,
	0x9e, 0xfc, 0x3f, 0x4d, 0x8e, 0x6c, 0x47, 0x51, 0x00, 0x83, 0xbf, 0x54, 0xaa, 0xd4, 0xaf, 0xbb,
	0xec, 0x1d, 0x5b, 0xae, 0xca, 0x7f, 0x9d, 0x4d, 0x3b, 0xfc, 0xa2, 0x25, 0x0c, 0x2b, 0x44, 0xb8,
	0x22, 0xe8, 0x43, 0x4b, 0x19, 0xbe, 0x00, 0xb2, 0x82, 0x71, 0x05, 0xc9, 0x17, 0x0a, 0x7d, 0x6a,
	0x8b, 0xeb, 0x7b, 0xd6, 0x8d, 0x0a, 0x61, 0xd2, 0x98, 0xa7, 0xdc, 0x50, 0xe4, 0x9e, 0x0f, 0xd6,
	0x5e, 0xdf, 0x6e, 0x6c, 0x00, 0x56, 0x40, 0x88, 0xca, 0xa1, 0xc9, 0x99, 0x28, 0x6f, 0xfe, 0xdc,
	0xca, 0x37, 0x7f, 0x65, 0x6b, 0xaa, 0xea, 0xf7, 0xa7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x46,
	0xa8, 0xf9, 0xd5, 0x03, 0x00, 0x00,
}
