// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/message.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SomeRequest struct {
	A                    uint32   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SomeRequest) Reset()         { *m = SomeRequest{} }
func (m *SomeRequest) String() string { return proto.CompactTextString(m) }
func (*SomeRequest) ProtoMessage()    {}
func (*SomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8368f5d77b0b9b7b, []int{0}
}

func (m *SomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SomeRequest.Unmarshal(m, b)
}
func (m *SomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SomeRequest.Marshal(b, m, deterministic)
}
func (m *SomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SomeRequest.Merge(m, src)
}
func (m *SomeRequest) XXX_Size() int {
	return xxx_messageInfo_SomeRequest.Size(m)
}
func (m *SomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SomeRequest proto.InternalMessageInfo

func (m *SomeRequest) GetA() uint32 {
	if m != nil {
		return m.A
	}
	return 0
}

type SomeResponse struct {
	A                    uint32   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SomeResponse) Reset()         { *m = SomeResponse{} }
func (m *SomeResponse) String() string { return proto.CompactTextString(m) }
func (*SomeResponse) ProtoMessage()    {}
func (*SomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8368f5d77b0b9b7b, []int{1}
}

func (m *SomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SomeResponse.Unmarshal(m, b)
}
func (m *SomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SomeResponse.Marshal(b, m, deterministic)
}
func (m *SomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SomeResponse.Merge(m, src)
}
func (m *SomeResponse) XXX_Size() int {
	return xxx_messageInfo_SomeResponse.Size(m)
}
func (m *SomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SomeResponse proto.InternalMessageInfo

func (m *SomeResponse) GetA() uint32 {
	if m != nil {
		return m.A
	}
	return 0
}

func init() {
	proto.RegisterType((*SomeRequest)(nil), "protobuf.SomeRequest")
	proto.RegisterType((*SomeResponse)(nil), "protobuf.SomeResponse")
}

func init() { proto.RegisterFile("protobuf/message.proto", fileDescriptor_8368f5d77b0b9b7b) }

var fileDescriptor_8368f5d77b0b9b7b = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x03, 0x0b, 0x08,
	0x71, 0xc0, 0xc4, 0x95, 0xa4, 0xb9, 0xb8, 0x83, 0xf3, 0x73, 0x53, 0x83, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x78, 0xb8, 0x18, 0x13, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0x18, 0x13,
	0x95, 0x64, 0xb8, 0x78, 0x20, 0x92, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0xa8, 0xb2, 0x46, 0x01,
	0x10, 0xad, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x8e, 0x5c, 0x02, 0x20, 0xae, 0x5b,
	0x69, 0x5e, 0x72, 0x49, 0x66, 0x7e, 0x9e, 0x5f, 0x62, 0x6e, 0xaa, 0x90, 0xa8, 0x1e, 0xcc, 0x22,
	0x3d, 0x24, 0x5b, 0xa4, 0xc4, 0xd0, 0x85, 0x21, 0xe6, 0x27, 0xb1, 0x81, 0x85, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x2d, 0x7a, 0xf6, 0xdc, 0xb7, 0x00, 0x00, 0x00,
}
