// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/room.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomRequest struct {
	RoomId               uint32   `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CreatorId            uint32   `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomRequest) Reset()         { *m = RoomRequest{} }
func (m *RoomRequest) String() string { return proto.CompactTextString(m) }
func (*RoomRequest) ProtoMessage()    {}
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbedac3b1c8da9d2, []int{0}
}

func (m *RoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRequest.Unmarshal(m, b)
}
func (m *RoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRequest.Marshal(b, m, deterministic)
}
func (m *RoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRequest.Merge(m, src)
}
func (m *RoomRequest) XXX_Size() int {
	return xxx_messageInfo_RoomRequest.Size(m)
}
func (m *RoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRequest proto.InternalMessageInfo

func (m *RoomRequest) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomRequest) GetCreatorId() uint32 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

type RoomInfoRequest struct {
	RoomId               uint32   `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CreatorId            uint32   `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Flow                 int64    `protobuf:"varint,3,opt,name=flow,proto3" json:"flow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfoRequest) Reset()         { *m = RoomInfoRequest{} }
func (m *RoomInfoRequest) String() string { return proto.CompactTextString(m) }
func (*RoomInfoRequest) ProtoMessage()    {}
func (*RoomInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbedac3b1c8da9d2, []int{1}
}

func (m *RoomInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfoRequest.Unmarshal(m, b)
}
func (m *RoomInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfoRequest.Marshal(b, m, deterministic)
}
func (m *RoomInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfoRequest.Merge(m, src)
}
func (m *RoomInfoRequest) XXX_Size() int {
	return xxx_messageInfo_RoomInfoRequest.Size(m)
}
func (m *RoomInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfoRequest proto.InternalMessageInfo

func (m *RoomInfoRequest) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomInfoRequest) GetCreatorId() uint32 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *RoomInfoRequest) GetFlow() int64 {
	if m != nil {
		return m.Flow
	}
	return 0
}

type RoomResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RoomId               uint32   `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CreatorId            uint32   `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Flow                 int64    `protobuf:"varint,4,opt,name=flow,proto3" json:"flow,omitempty"`
	TimeUsed             int64    `protobuf:"varint,5,opt,name=time_used,json=timeUsed,proto3" json:"time_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomResponse) Reset()         { *m = RoomResponse{} }
func (m *RoomResponse) String() string { return proto.CompactTextString(m) }
func (*RoomResponse) ProtoMessage()    {}
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbedac3b1c8da9d2, []int{2}
}

func (m *RoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomResponse.Unmarshal(m, b)
}
func (m *RoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomResponse.Marshal(b, m, deterministic)
}
func (m *RoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomResponse.Merge(m, src)
}
func (m *RoomResponse) XXX_Size() int {
	return xxx_messageInfo_RoomResponse.Size(m)
}
func (m *RoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomResponse proto.InternalMessageInfo

func (m *RoomResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *RoomResponse) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomResponse) GetCreatorId() uint32 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *RoomResponse) GetFlow() int64 {
	if m != nil {
		return m.Flow
	}
	return 0
}

func (m *RoomResponse) GetTimeUsed() int64 {
	if m != nil {
		return m.TimeUsed
	}
	return 0
}

type ChangeResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Num                  int64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeResponse) Reset()         { *m = ChangeResponse{} }
func (m *ChangeResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeResponse) ProtoMessage()    {}
func (*ChangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbedac3b1c8da9d2, []int{3}
}

func (m *ChangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeResponse.Unmarshal(m, b)
}
func (m *ChangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeResponse.Marshal(b, m, deterministic)
}
func (m *ChangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeResponse.Merge(m, src)
}
func (m *ChangeResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeResponse.Size(m)
}
func (m *ChangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeResponse proto.InternalMessageInfo

func (m *ChangeResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ChangeResponse) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*RoomRequest)(nil), "protobuf.RoomRequest")
	proto.RegisterType((*RoomInfoRequest)(nil), "protobuf.RoomInfoRequest")
	proto.RegisterType((*RoomResponse)(nil), "protobuf.RoomResponse")
	proto.RegisterType((*ChangeResponse)(nil), "protobuf.ChangeResponse")
}

func init() { proto.RegisterFile("protobuf/room.proto", fileDescriptor_dbedac3b1c8da9d2) }

var fileDescriptor_dbedac3b1c8da9d2 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0x4d, 0xd2, 0xf1, 0x93, 0x15, 0x6b, 0xac, 0x08, 0x25, 0xa7, 0x9e, 0x22, 0xe8,
	0x45, 0x04, 0x85, 0x22, 0x2a, 0xb9, 0xae, 0xf4, 0x28, 0x25, 0xed, 0x4e, 0x34, 0x60, 0x32, 0x31,
	0xbb, 0xa9, 0xbf, 0xc1, 0x93, 0x7f, 0x59, 0x76, 0x9b, 0xd2, 0x58, 0x68, 0x05, 0xbd, 0xcd, 0xbc,
	0x37, 0xf3, 0xde, 0xdb, 0x1d, 0x38, 0x2c, 0x4a, 0x52, 0x34, 0xa9, 0x92, 0xf3, 0x92, 0x28, 0x0b,
	0x4d, 0xc7, 0xbc, 0x05, 0x18, 0xdc, 0xc3, 0x36, 0x27, 0xca, 0x38, 0xbe, 0x57, 0x28, 0x15, 0x3b,
	0x06, 0x57, 0x8f, 0x8d, 0x53, 0xe1, 0x5b, 0x7d, 0x6b, 0xb0, 0xcb, 0x1d, 0xdd, 0x46, 0x82, 0x9d,
	0x01, 0x4c, 0x4b, 0x8c, 0x15, 0x95, 0x9a, 0x6b, 0x19, 0xae, 0x53, 0x23, 0x91, 0x08, 0x9e, 0x61,
	0x5f, 0xcb, 0x44, 0x79, 0x42, 0xff, 0x94, 0x62, 0x0c, 0xda, 0xc9, 0x1b, 0x7d, 0xf8, 0x76, 0xdf,
	0x1a, 0xd8, 0xdc, 0xd4, 0xc1, 0x97, 0x05, 0x3b, 0xf3, 0x98, 0xb2, 0xa0, 0x5c, 0x22, 0xeb, 0x82,
	0x23, 0x55, 0xac, 0x2a, 0x69, 0xb4, 0x3d, 0x5e, 0x77, 0x4d, 0xd3, 0xd6, 0x06, 0x53, 0x7b, 0x9d,
	0x69, 0x7b, 0x69, 0xca, 0x4e, 0xa1, 0xa3, 0xd2, 0x0c, 0xc7, 0x95, 0x44, 0xe1, 0x6f, 0x19, 0xc2,
	0xd3, 0xc0, 0x48, 0xa2, 0x08, 0xae, 0x61, 0xef, 0xee, 0x35, 0xce, 0x5f, 0xf0, 0xd7, 0x48, 0x07,
	0x60, 0xe7, 0x55, 0x66, 0xe2, 0xd8, 0x5c, 0x97, 0x17, 0x9f, 0xad, 0xf9, 0xa7, 0x3f, 0x61, 0x39,
	0x4b, 0xa7, 0xc8, 0xae, 0xc0, 0x7d, 0x44, 0xa5, 0x11, 0x76, 0x14, 0x2e, 0x2e, 0x13, 0x36, 0xce,
	0xd2, 0xeb, 0xae, 0xc2, 0xb5, 0xe7, 0x2d, 0xb8, 0x43, 0x21, 0xcc, 0xe6, 0xc9, 0xcf, 0x91, 0xc6,
	0x25, 0x7a, 0xfe, 0x92, 0x5a, 0xc9, 0x3c, 0x04, 0x18, 0x15, 0x22, 0x56, 0xf8, 0xa0, 0x1f, 0xfc,
	0x27, 0x89, 0x1b, 0x00, 0x8e, 0x19, 0xcd, 0x70, 0x53, 0xfe, 0xb5, 0xeb, 0x13, 0xc7, 0x10, 0x97,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xc6, 0xef, 0xdb, 0xa7, 0x02, 0x00, 0x00,
}
